Request more storage in tests due to the required minimal size on Ionos managed k8s (#184)
# Description

When running these tests on Ionos managed k8s provisioning of the PVCs failed with this error:

message: 'failed to provision volume with StorageClass "ionos-enterprise-hdd": rpc
  error: code = OutOfRange desc = Requested size 536870912 must be between 1073741824
  and 4398046511104 bytes'

This PR increases the size of all requested PVCs to 2Gi to see if the tests finish then.